<?php
declare(strict_types=1);

namespace MauticPlugin\MauticMultidomainBundle\EventListener;

use Mautic\CoreBundle\Helper\CoreParametersHelper;
use Doctrine\DBAL\Connection;
use Mautic\CoreBundle\Helper\ClickthroughHelper;
use Mautic\EmailBundle\EmailEvents;
use Mautic\EmailBundle\Event\EmailSendEvent;
use Mautic\EmailBundle\Helper\MailHelper;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class EmailSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private CoreParametersHelper $coreParametersHelper,
        private ?Connection $connection = null,
    )
    {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            EmailEvents::EMAIL_ON_SEND    => [
                ['onEmailSend', 0],
                ['onEmailFinalize', -10000],
            ],
            EmailEvents::EMAIL_ON_DISPLAY => ['onEmailDisplay', 0],
        ];
    }

    public function onEmailSend(EmailSendEvent $event): void
    {
        $senderDomain = $this->resolveSenderDomain($event);
        if (null === $senderDomain) {
            return;
        }

        $emailTrackingDomain = $this->resolveConfiguredTrackingDomain($event);
        $trackingDomain = $emailTrackingDomain ?? $senderDomain;

        if ($this->isAllowedDomain($trackingDomain)) {
            $this->rewriteDomains($event, $trackingDomain);
            $this->rewriteTrackingPixel($event, $trackingDomain);
        }
    }
    /**
     * Rewrites the redirect tokens generated by Mautic after the initial send hook.
     */
    public function onEmailFinalize(EmailSendEvent $event): void
    {
        $senderDomain = $this->resolveSenderDomain($event);
        if ($senderDomain === null) {
            return;
        }

        $emailTrackingDomain = $this->resolveConfiguredTrackingDomain($event);
        $trackingDomain = $emailTrackingDomain ?? $senderDomain;
        if (!$this->isAllowedDomain($trackingDomain)) {
            return;
        }

        $this->rewriteDomains($event, $trackingDomain);
        $this->rewriteGeneratedTokenUrls($event, $trackingDomain);
        $this->rewriteTrackingPixel($event, $trackingDomain);
    }



    private function resolveConfiguredTrackingDomain(EmailSendEvent $event): ?string
    {
        if ($this->connection === null) {
            return null;
        }

        try {
            $source = $event->getSource();
            if (($source[0] ?? null) === 'campaign.event') {
                $eventId = filter_var($source[1] ?? null, FILTER_VALIDATE_INT);
                if ($eventId !== false && $eventId > 0) {
                    $domain = $this->connection->fetchOne(
                        'SELECT r.tracking_domain FROM smr_campaign_routing r INNER JOIN campaign_events e ON e.campaign_id = r.campaign_id WHERE e.id = :event_id',
                        ['event_id' => $eventId]
                    );
                    if (is_string($domain) && $this->normalizeDomain($domain) !== null) {
                        return $this->normalizeDomain($domain);
                    }
                }
            }

            $emailId = $event->getEmail()?->getId();
            if ($emailId === null || $emailId <= 0) {
                return null;
            }

            $domain = $this->connection->fetchOne(
                'SELECT tracking_domain FROM smr_email_routing WHERE email_id = :email_id',
                ['email_id' => $emailId]
            );
        } catch (\Throwable) {
            return null;
        }

        return is_string($domain) ? $this->normalizeDomain($domain) : null;
    }

    private function rewriteTrackingPixel(EmailSendEvent $event, string $trackingDomain): void
    {
        $helper = $event->getHelper();
        if (!$helper instanceof MailHelper || !$helper->getIdHash()) {
            return;
        }

        $pixelUrl = 'https://'.$trackingDomain.'/email/'.rawurlencode((string) $helper->getIdHash()).'.gif?ct='
            .ClickthroughHelper::encodeArrayForUrl(['sent_time' => time()]);

        $event->addToken('{tracking_pixel}', $pixelUrl);
    }

    private function rewriteGeneratedTokenUrls(EmailSendEvent $event, string $trackingDomain): void
    {
        $siteUrl = rtrim((string) $this->coreParametersHelper->get('site_url'), '/');
        if ($siteUrl === '') {
            return;
        }

        foreach ($event->getTokens(false) as $token => $value) {
            if (is_string($value) && str_contains($value, $siteUrl)) {
                $event->addToken((string) $token, str_replace($siteUrl, 'https://'.$trackingDomain, $value));
            }
        }
    }


    public function onEmailDisplay(EmailSendEvent $event): void
    {
        // When viewing the email in the browser
        // Email display hooks are kept for future display-time domain customizations.
        // Runtime site_url mutation is intentionally not used in Mautic 7.
    }

    private function resolveSenderDomain(EmailSendEvent $event): ?string
    {
        $email = $event->getEmail();
        if (!$email) {
            return null;
        }

        // Sender precedence: Email-level FROM, then global Mautic mailer_from_email.
        $fromAddress = $email->getFromAddress() ?: $this->coreParametersHelper->get('mailer_from_email');
        if (empty($fromAddress)) {
            return null;
        }

        return $this->extractDomainFromAddress((string) $fromAddress);
    }

    private function rewriteDomains(EmailSendEvent $event, string $senderDomain): void
    {
        $defaultSiteUrl = (string) $this->coreParametersHelper->get('site_url');
        if ('' === $defaultSiteUrl) {
            return;
        }

        $parsedUrl = parse_url($defaultSiteUrl);
        if (!is_array($parsedUrl) || !isset($parsedUrl['host'])) {
            return;
        }

        $scheme      = (string) ($parsedUrl['scheme'] ?? 'https');
        $defaultHost = (string) $parsedUrl['host'];
        $port        = isset($parsedUrl['port']) ? (int) $parsedUrl['port'] : null;

        if ($senderDomain === $defaultHost) {
            return;
        }

        $content = $event->getContent();
        $plainText = $event->getPlainText();

        $baseToReplace = $scheme . '://' . $defaultHost;
        $newBaseUrl    = $scheme . '://' . $senderDomain;

        if (null !== $port) {
            $baseToReplace .= ':' . $port;
            $newBaseUrl .= ':' . $port;
        }

        if ($content) {
            $content = str_replace($baseToReplace, $newBaseUrl, $content);
            $event->setContent($content);
        }

        if ($plainText) {
            $plainText = str_replace($baseToReplace, $newBaseUrl, $plainText);
            $event->setPlainText($plainText);
        }
    }

    private function extractDomainFromAddress(string $address): ?string
    {
        $normalizedAddress = trim($address);
        if ('' === $normalizedAddress) {
            return null;
        }

        if (preg_match('/<([^>]+)>/', $normalizedAddress, $matches)) {
            $normalizedAddress = trim($matches[1]);
        }

        $parts = explode('@', $normalizedAddress);
        if (count($parts) < 2) {
            return null;
        }

        $domain = $this->normalizeDomain((string) end($parts));

        return $domain;
    }

    private function isAllowedDomain(string $domain): bool
    {
        $allowedDomains = $this->getAllowedDomains();
        if ([] === $allowedDomains) {
            return false;
        }

        foreach ($allowedDomains as $allowedDomain) {
            if ($domain === $allowedDomain || str_ends_with($domain, '.'.$allowedDomain)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return string[]
     */
    private function getAllowedDomains(): array
    {
        $allowedDomainsString = (string) $this->coreParametersHelper->get('allowed_domains', '');
        if ('' === trim($allowedDomainsString)) {
            return [];
        }

        $domains = preg_split('/[\s,]+/', $allowedDomainsString) ?: [];
        $normalizedDomains = [];

        foreach ($domains as $domain) {
            $normalizedDomain = $this->normalizeDomain($domain);
            if (null === $normalizedDomain) {
                continue;
            }

            $normalizedDomains[$normalizedDomain] = $normalizedDomain;
        }

        return array_values($normalizedDomains);
    }

    private function normalizeDomain(string $domain): ?string
    {
        $domain = strtolower(trim($domain));
        $domain = preg_replace('#^https?://#', '', $domain) ?? $domain;
        $domain = preg_replace('#/.*$#', '', $domain) ?? $domain;
        $domain = preg_replace('#:\d+$#', '', $domain) ?? $domain;
        $domain = trim($domain, '.');

        return '' === $domain ? null : $domain;
    }
}
